theme/package.json, theme/src/components/details.js, theme/src/components/nav-drawer.js, theme/src/components/nav-dropdown.js, yarn.lock
All the dropdowns are stuck open in Edge because Edge doesn't support the `<details>` element 😢 
Use [`details-element-polyfill`](https://www.npmjs.com/package/details-element-polyfill) to polyfill the `<details>` element for Edge. 
For now, I copied the [`Details`](https://github.com/primer/blueprints/blob/master/src/Details.js) component from Blueprints. When the `Details` component is updated  in`@primer/components`  `v14.0.0`, we should switch to using that.
=> Fix details component in Edge

docs/content/components/do-dont.mdx, docs/src/@primer/gatsby-theme-doctocat/live-code-scope.js, docs/src/@primer/gatsby-theme-doctocat/nav.yml, theme/index.js, theme/src/components/do-dont.js
We don't want people to need to know how to use the `Grid` component to create Do/Don't example.
I created a `DoDont` wrapper component to handle the layout for the Do/Don't example. The new Do/Don't API looks like this:
```jsx
<DoDont>
<Do src="url">
text caption
</Do>
<Dont src="url">
text caption
</Dont>
</DoDont>
```
instead of:
```jsx
<Grid gridTemplateColumns={['1fr', '1fr', '1fr 1fr']} gridGap={3}>
<Do src="url">
text caption
</Do>
<Dont src="url">
text caption
</Dont>
</Grid>
```
=> Create a DoDont wrapper component

theme/package.json, theme/src/components/nav-drawer.js
I recently added a flex container inside the navigation drawer which broke its layout on mobile. This pull request fixes that issue by using the `flex` property to ensure nothing shrinks unexpectedly. 
<details>
<summary><strong>Before</strong></summary>
</details>
<details>
<summary><strong>After</strong></summary>
</details>
=> Fix nav drawer

docs/content/usage/customization.mdx, theme/gatsby-node.js, theme/src/components/nav-items.js
Primer documentation sites don't make it easy to navigate to the GitHub repository associated with a particular site. For example, https://primer.style/css doesn't have a link to https://github.com/primer/css
Doctocat now uses the `repository` field from `package.json` to automatically add a `GitHub` link to the sidebar:
Closes #21
=> Add GitHub link to the sidebar

theme/gatsby-node.js
I tried to run doctocat in develop mode on my Windows box, and ran into the following issue when I tried to bring up the site at http://localhost:8000 
It turned out to be related to \ being returned by the nodes representing the mdx files in ```createPages```.
Replacing the \ with / seems to fix the issue for the ```pagePath```, but there may be other places where a similar fix is needed.
It would be interesting to know if other themes or places that use Gatsby's createPages do something similar? If so, maybe we should open an issue in Gatsby.
Also, I didn't test on a non-Windows machine - I think the fix should be fine there, but maybe someone should double-check 😁
=> Replace \ with / in page paths to get Doctocat working on Windows.

theme/src/components/code.js
The font size of code examples is not consistent on mobile browsers. In some code examples the font size is much too large.
This pull request adjusts the way that font-size is applied to code examples. Now, the font size is the same in all code examples across all browsers. I'm guessing the issue might have been a weird inheritance bug.
| --- | --- |
| <img src="https://user-images.githubusercontent.com/4608155/64363584-e7719b80-cfc5-11e9-8b05-73f55150cb6d.PNG" /> | ![IMG_5322](https://user-images.githubusercontent.com/4608155/64364662-39b3bc00-cfc8-11e9-8640-b7d109d4ae0c.PNG) |
=> Fix code example font size on mobile

theme/src/components/header.js
This pull request ensures that we only display the mobile search button in the header if the `isSearchEnabled` prop is set to `true`. This is important for the header to work on primer.style.
=> Only show mobile search if search is enabled

theme/package.json, theme/src/components/live-code.js
This PR removes the overflow hidden style that was causing some styling issues in the Primer Components docs. Also updates the version number ✨ 
Fixes: #89
=> Remove overflow hidden style

theme/package.json, theme/src/use-search.js
- Fixes global graphql usage (thanks @shawnbot !) #86 
- Fixes exhaustive-deps violation in useSearch hook
`53:6  warning  React Hook React.useEffect has missing dependencies: 'fuse' and 'list'. Either include them or remove the dependency array  react-hooks/exhaustive-deps`
=> Fix a few warnings in use-search hook.

theme/package.json
Primer Components and Gatsby both rely on the `^16.9.0` range of `react` and `react-dom`, which may be causing some peer dependency issues in projects using those libraries. Bumping up to `^16.9.0`
=> Bump react dep

theme/src/components/container.js, theme/src/components/skip-link.js, theme/src/components/wrap-page-element.js
Github.com:
Doctocat:
Closes #82 
Saves 21 tabs to get to main content on Doctocat site!
=> Skip link to allow user to skip to page content.

README.md, docs/content/index.mdx
Doctocat is no longer "experimental". It now powers all of our `primer.style` documentation sites.
=> Remove experimental warning

theme/package.json, theme/src/components/header.js, theme/src/components/nav-drawer.js, yarn.lock
Copied from https://github.com/primer/components/issues/691:
> Hi friends, I think I found a little bug in the documentation website, which results in the page becoming unclickable.
> 
> **Reproduction Steps:**
> Step 1. Open https://primer.style/components/ on PC
> Step 2. Resize window until hamburger menu on top-right appears, then click on it.
> Step 3. Without pressing anything else, resize the window back wide enough that the hamburger menu disappears, the page is now unclickable, unscrollable, etc.
This happens because we open an overlay on the page when opening the drawer, but resizing the window only causes the drawer element to disappear because of breakpoints, and we don't ever actually close the drawer. This PR adds a hook for the drawer that ensures that it gets closed when …
=> Fix broken page when resizing with drawer open

theme/gatsby-node.js
Something about the way HMR runs is causing every build except the first one to have a missing `frontmatter` property in the page context; this PR adds the frontmatter explicitly, ensuring it always exists.
This PR also fine tunes the way we look up contributor data from GitHub:
* If `GITHUB_TOKEN` is not set, no API call will be made
* Results from the API are stored in an in-memory cache to cut down on requests during development
=> Fix "cannot read property 'title' of undefined" after HMR

theme/package.json, theme/src/components/dark-button.js, theme/src/components/dark-text-input.js
This PR updates the dark inputs and buttons to set no box-shadow. The visual refresh in Primer Components adds some box-shadows that look weird with these dark variants. 
We'll need to ship these changes now, so that we can use the new doctocat version in the Primer Components visual refresh PR 😸It's safe to ship these now without updating Primer Components in this repo because there was no box-shadow before, so adding `box-shadow: none` doesn't make any difference.
=> Updates for Component Refresh

docs/content/usage/live-code.mdx, theme/src/components/code.js, theme/src/components/live-code.js
It would be nice to be able to include more complex examples on documentation pages; for this, it would be useful to have access to the `noInline` prop. Here's an example of how this could be useful from some documentation I'm working on:
```javascript
function CaretSelector(props) {
return [
'top',
'bottom',
'left',
'right',
'bottom-left',
'bottom-right',
'top-left',
'top-right',
'left-bottom',
'left-top',
'right-bottom',
'right-top'
].map((dir) => (
<>
<input type="radio" name="caret" 
value={dir} key={dir} selected={dir === props.current}
onClick={() => props.onChange(dir)} /> {dir}
</>
))
}
function Demo(props) {
const [pos, setPos] = React.useState('top')
return (
<Relative>
<CaretSelector current={pos} onChange={setPos} />
<Text textAlign="center" display="block"> …
```
=> Add support for `noInline` on live code editors

LICENSE
=> Adding the MIT license to doctocat

theme/src/primer-nav.yml
This updates the Octicons link in the header from `octicons.github.com` to `primer.style/octicons`
=> Update Octicons link in Primer nav

docs/package.json, theme/package.json, theme/src/components/live-code.js, yarn.lock
This PR updates the version of @primer/components that Doctocat uses to `16.1.0`. Version `16` of @primer/components introduced a visual refresh for components like buttons and inputs ✨
=> Use @primer/components 16.1.0

theme/gatsby-node.js, theme/package.json, theme/src/components/header.js, theme/src/components/heading.js, theme/src/components/layout.js, theme/src/components/sidebar.js, theme/src/components/table-of-contents.js
The table of contents takes up a lot of room at the top of our Primer documentation pages:
This PR moves the table of contents into a sticky sidebar so it doesn't push the main content below the fold:
On mobile, the table of contents collapses into a details element:
| Collapsed | Expanded |
| --- | --- | 
| ![primer-components-lak1zacvj now sh_components_core-concepts(iPhone 5_SE)](https://user-images.githubusercontent.com/4608155/78165945-eb04be00-7400-11ea-9f59-5859c9006721.png) | ![primer-components-lak1zacvj now sh_components_core-concepts(iPhone 5_SE) (1)](https://user-images.githubusercontent.com/4608155/78166003-ffe15180-7400-11ea-9f88-f88d75fb5d4a.png) |
---
Part of #120
=> Update table of contents

theme/gatsby-node.js, theme/package.json
f25f74decd21649592c074c9e97624a614406525 introduced a check insuring that `GITHUB_TOKEN` was set before fetching contributor data from GitHub, as running in dev mode without a token generated a lot of requests which started timing out, slowing the build, and logging a lot of errors. However, since `GITHUB_TOKEN` isn't set during deploys, this means that contributors are never fetched during Now deployments.
This PR allows tokenless fetching of contributor information during Now deployments; in the future, we may create and manage a token that we can install via [secrets](https://zeit.co/docs/v2/build-step#using-environment-variables-and-secrets).
=> Enable fetching contributors without token on deploy

theme/src/components/live-code.js
Makes use of React's `useState` hook to provide the `<ClipboardCopy>` component with an updated snippet from the live text editor.
=> ClipboardCopy now copies updated live code

theme/package.json, theme/src/components/live-code.js
Hiding the overflow in the live code containers breaks some of the demos that have elements that spill out of the container; see https://primer.style/components/Dropdown for an example.
=> Remove `overflow: hidden` from live code container

theme/src/primer-nav.yml
This PR changes the Primer Components naming in the top nav to be Primer React :)
=> Rename Primer Components to Primer React

docs/content/usage/customization.mdx
When running `gatsby develop`, the CLI was returning an error. 
```
ERROR #98123  WEBPACK
Generating development JavaScript bundle failed
~/docs/src/@primer/gatsby-theme-doctocat/components/hero.js
6:5  error  'React' must be in scope when using JSX  react/react-in-jsx-scope
✖ 1 problem (1 error, 0 warnings)
File: src/@primer/gatsby-theme-doctocat/components/hero.js
failed Re-building development bundle - 1.190s
```
Adding this line fixes the error.
=> fix: ERROR #98123 when `gatsby develop` with shadowed hero.js

theme/gatsby-node.js, theme/src/components/layout.js, theme/src/components/table-of-contents.js
This PR addresses the table of contents feedback in https://github.com/primer/doctocat/issues/137. Here's what changed:
👉   [Preview](https://doctocat-git-toc-updates.primer.vercel.app/doctocat/)
| --- | --- |
|  ![](https://firebasestorage.googleapis.com/v0/b/firescript-577a2.appspot.com/o/imgs%2Fapp%2Fcolebemis%2FyOClhhgVYR.png?alt=media&token=f537ac7c-1702-459c-8dae-474da9ecafef) | ![](https://firebasestorage.googleapis.com/v0/b/firescript-577a2.appspot.com/o/imgs%2Fapp%2Fcolebemis%2FgzoRT1KKGv.png?alt=media&token=899d53ec-afa6-4476-a35a-a677b41cde3d)|
| --- | --- |
| ![](https://firebasestorage.googleapis.com/v0/b/firescript-577a2.appspot.com/o/imgs%2Fapp%2Fcolebemis%2Fcx3X6099F-.png?alt=media&token=02642c90-5c7c-4ff1-a7e7-7cc2101e7d0b) | …
=> Table of contents updates

theme/gatsby-node.js, theme/src/components/hero-layout.js, theme/src/components/layout.js
When making changes to a `.md` or `.mdx` page in a Doctocat site, this error appears:
This error occurs because `gatsby-plugin-mdx` should insert `frontmatter` in the page context of every page, and does on the first build, but when HMR kicks in the frontmatter is lost.
This is a known bug in gatsby-plugin-mdx: https://github.com/gatsbyjs/gatsby/issues/21837
- Solution 1: Explicitly add `frontmatter` to the page context in our local `gatsby-node.js` instead of relying on `gatsby-plugin-mdx` to handle `frontmatter` for us (This is the solution implemented in this PR)
- Solution 2: Fix `gatsby-plugin-mdx` so that it correctly sets the `frontmatter` when a page is hot reloaded.
@BinaryMuse had previously implemented this solution in https://github.com/primer/doctocat/pull/116. However, the …
=> Fix hot module reloading

theme/src/components/nav-drawer.js
The dark "Primer" section of the responsive navigation drawer stretches on when the viewport is taller than the content.
Applying `flex: 0 0 auto` to that section fixed the issue.
| --- | --- |
| ![image](https://user-images.githubusercontent.com/4608155/91345246-e9fb7100-e793-11ea-9e02-9ff096679def.png) | ![image](https://user-images.githubusercontent.com/4608155/91756044-f65f3f80-eb80-11ea-9771-f2098a502c54.png) |
Closes #168
=> Fix responsive navigation drawer on tall screens

docs/package.json, theme/package.json, theme/src/components/details.js, theme/src/components/sidebar.js, yarn.lock
When we click on a page in the navigation, if the navigation is really long (lots of items, example: https://primer.style/css/), the navigation goes back to the top on page load.
This PR implements a React hook to persist the scroll position of the sidebar. It does this by saving the scroll position of the sidebar on every scroll event and restoring that scroll position when the component remounts after a page change.
Closes #122 
Thanks for your help on this one, @BinaryMuse! ✨
=> Persist sidebar scroll position on page change

theme/gatsby-node.js, theme/package.json
In https://github.com/primer/doctocat/pull/175, I introduced a bug that caused site [builds to fail](https://vercel.com/primer/primer-components/ln2bvpaek) if their markdown files didn't have specific frontmatter variables. This occurred because I added more frontmatter variables to the GraphQL request used to create pages in order to pass them to the page context. However, if we request a frontmatter variable that doesn't exist in any markdown files in the site, the build fails.
Instead of getting frontmatter from a GraphQL request, I used utility functions from `gatsby-plugin-mdx` to extract frontmatter variables from the raw MDX code. This is a workaround until https://github.com/gatsbyjs/gatsby/issues/21837 is fixed.
=> Fix frontmatter GraphQL error

theme/package.json, theme/src/search.worker.js, theme/src/use-search.js, yarn.lock
Currently, we run a [Fuse](https://fusejs.io/) query on the main thread when the user enters a search term. This causes a lot of GC and some page jank.
This PR moves the Fuse search into the background via web workers. In my testing, this reduced event handler run time from hundreds of milliseconds to around 10.
=> Perform seach in the background

docs/content/usage/customization.mdx, theme/gatsby-node.js, theme/package.json
This PR updates Doctocat to work with projects that use something other than `master` for their default branch. The only change I needed to make was with the `Edit this on GitHub` link which assumed that the default branch was `master`. We now allow passing a `defaultBranch` option to the `options` object in `gatsby-config.js`
Addresses: https://github.com/primer/components/issues/876
=> Allow for default branches other than 'master' 

.changeset/config.json, package.json, yarn.lock
This PR sets the changesets changelog format to [`@changesets/changelog-github`](https://github.com/atlassian/changesets/tree/master/packages/changelog-github).  The `@changesets/changelog-github` format gives credit to contributors, unlike the default format.
| Default | @changesets/changelog-github |
| --- | --- |
|  ![image](https://user-images.githubusercontent.com/4608155/94746172-ff366300-0330-11eb-92f2-d9433e073894.png) | ![image](https://user-images.githubusercontent.com/4608155/94746220-1bd29b00-0331-11eb-9837-d95554be1d8d.png) |
=> Modify changesets changelog format

.changeset/curly-hats-grow.md, theme/gatsby-node.js
Contributor data wasn't being shown on some Doctocat sites:
Contributor data is only fetched when a `GITHUB_TOKEN` environment variable is defined or during a deploy build. We were using the `NOW_GITHUB_DEPLOYMENT` environment variable to detect deploy builds. However, Vercel recently renamed the `NOW_GITHUB_DEPLOYMENT` environment variable to `VERCEL_GITHUB_DEPLOYMENT` so we didn't detect deploy builds anymore.
This PR adds a check for `VERCEL_GITHUB_DEPLOYMENT` so we fetch contributor data on deploy builds again.
cc @yaili
=> Fetch contributor data on deploy builds again

.github/workflows/ci.yml
When we replaced our [`@primer/publish`](https://github.com/primer/publish) workflow with [changesets]() in https://github.com/primer/doctocat/pull/189, we lost the canary builds that `@primer/publish` released for every commit. These canary releases were helpful for testing changes in other projects before the pull request was merging the changes into the main branch.
This PR updates our CI workflow to publish [snapshot releases](https://github.com/atlassian/changesets/blob/master/docs/snapshot-releases.md) (i.e. canary releases) for every commit.
Shoutout to @BinaryMuse for finding the snapshot releases docs! ✨
=> Add snapshot releases to CI workflow

.changeset/pretty-ligers-lay.md, theme/src/primer-nav.yml
This PR adds a https://primer.style/mobile link to the global navigation.
=> Add /mobile to global navigation

.changeset/gold-eagles-wink.md, theme/src/primer-nav.yml
This PR adds a https://primer.style/view-components link to the global navigation.
=> Add /view-components to global navigation

.changeset/silver-wolves-play.md, theme/src/components/page-footer.js
@yaili noticed that there's a border-radius on the bottom of Doctocat pages:
This PR fixes that.
=> Remove border-radius on bottom border

.changeset/lazy-camels-search.md, theme/src/primer-nav.yml
Removes the prototyping link from the design dropdown in the global navigation.
=> Remove prototyping link from design dropdown

.changeset/rude-beans-shave.md, theme/src/primer-nav.yml
This PR adds a https://primer.style/desktop link to the global navigation.
=> Add /desktop to global navigation

.changeset/forty-cameras-peel.md, theme/package.json, theme/src/components/code.js, theme/src/components/live-code.js, theme/src/github.js, theme/src/prism.js, yarn.lock
This PR adds support for `ruby` and `erb` syntax highlighting in code examples:
````
```erb
<h1 class="hi">foo</h1>
<%= render(Primer::SpinnerComponent.new) %>
```
````
Closes https://github.com/primer/doctocat/issues/200
=> Add syntax highlighting support for ruby and erb

.changeset/two-ghosts-prove.md, theme/src/components/header.js
This PR replaces the `>` in the header with a `/` because `/` is more consistent with how we represent hierarchy at GitHub.
| --- | --- |
| ![image](https://user-images.githubusercontent.com/4608155/110138134-811a3480-7d86-11eb-9982-16b06732afea.png) |  ![image](https://user-images.githubusercontent.com/4608155/110138199-91321400-7d86-11eb-9a8d-b02152f3db4f.png) |
=> Replace > with / in header

.changeset/stale-hotels-admire.md, docs/content/usage/front-matter.mdx, theme/src/components/status-label.js
The meaning of the status values has proven to be confusing to some consumers.
Update the status values to follow the conventional alpha, beta, stable, deprecated cycle.
This is arguably a breaking change in that the default values are decorated with a color in the theme and consumers that pull in this change will need to switch to this new naming to keep the colors we provide. Consumers can choose to not use this scheme if they are comfortable with grey dots.
Co-authored-by: Joel Hawksley <joelhawksley@github.com>
=> Update status enum to use more conventional naming

.changeset/beige-keys-boil.md, theme/gatsby-node.js
The table of contents can get very long on pages with a lot of headings.
This PR updates the table of contents to only display `h2`s (previously we also displayed `h3`s). 
| --- | --- |
| ![image](https://user-images.githubusercontent.com/4608155/110140872-6a291180-7d89-11eb-915f-ac8e57a87936.png) | ![image](https://user-images.githubusercontent.com/4608155/110141030-95abfc00-7d89-11eb-9d60-d9573410831f.png) |
Closes https://github.com/primer/doctocat/issues/206
=> Reduce table of contents depth

.changeset/sharp-boats-knock.md, docs/content/components/index.mdx, docs/content/usage/customization.mdx, theme/src/components/wrap-root-element.js, theme/src/mdx-components.js
Doctocat provides a few React [components](/components) that are globally available in all `.md` and `.mdx` files (no import required). This PR makes it possible for consumers to add their own custom components to this list of globally available components.
This will allow us to use the [`Props`](https://github.com/primer/react/blob/main/docs/src/props.js) and `ComponentChecklist` components in the Primer React docs without importing them in every markdown file.
=> Allow custom MDX components

.changeset/fifty-rocks-complain.md, theme/src/components/layout.js
Increase the height to match biggest ``padding`` set by screen media CSS
Before:
After:
=> Fix scroll flickering of table of contents

docs/content/components/caption.mdx, docs/content/components/do-dont.mdx, docs/content/components/note.mdx, theme/gatsby-node.js
We need a way to get component statuses from the [ViewComponent](https://primer.style/view-components) and [React](https://primer.style/react) libraries to build a [cross-implementation status page](https://github.com/github/primer/issues/114).
This PR adds a step to the Doctocat build process that will output a `components.json` file with component status info if the site that its building has markdown files containing `componentId` frontmatter. Example:
[primer/react](https://github.com/primer/react): `docs/content/Avatar.mdx`
```md
---
componentId: avatar
status: Alpha
source: #
---
...
```
↓
```
gatsby build
```
↓
`https://primer.style/react/components.json`
```js
[
{
id: 'avatar',
path: '/Avatar',
status: 'alpha'
},
...
]
```
---
Co-author: @pouretrebelle
=> Output components.json file

.changeset/tame-students-prove.md, theme/gatsby-node.js
Adds another filter guard to post-build step query that is used to generate the components.json.
If frontmatter doesn't include _both_ `componentId` and `status`, the `components.json` doesn't get built. This prevents the [status page ](https://primer.style/status/) from being displayed. 
I'm proposing that you make status a required parameter too, to ensure we don't fail the creation of that file on the basis of a single file having a missing property.
=> fix: guard against missing status property in front-matter

.changeset/dynamic-live-scope.md, theme/src/components/code.js, theme/src/components/live-code.js
- Supports https://github.com/primer/react/pull/1785
By making `scope` a function, we can support scope based on metastring
example:
```
```jsx live drafts
```
=> LiveCode: Allow scope to be a function

.changeset/clever-lions-kiss.md, docs/content/components/do-dont.mdx, theme/src/components/do-dont.js
This PR updates some small visual styles, and adds an `indented` prop to the `Do` and `Dont` components. These changes aim to increase the clarity of when an example message appears within the documentation.
More design details behind this proposal can be seen on [this Figma file](https://www.figma.com/file/dsaSEL7aUeAgwksWZdiBIw/FY22-Q3---PageLayout-%2B-SplitPageLayout?node-id=17%3A9144) (only available for hubbers).
=> Update do/dont visual style, add `indented` prop

.changeset/quick-berries-fry.md, theme/src/components/link.js, theme/src/components/wrap-root-element.js
Giving our links in our markdown documents the underline style.
**Before**
**After**
=> Update the link styling for primer.style

.changeset/lemon-pants-mate.md, docs/content/components/do-dont.mdx, theme/gatsby-node.js, theme/src/components/layout.js
Add the `a11yReviewed` boolean data to the components.json static files generated onPostBuild.
- Add the frontmatter `a11yReviewed` variable to flag accessible components in PVC and PRC
- Use the generated `components.json` files to add an accessible `Label` component in the `primer.style/status` section
- https://github.com/github/primer/issues/1212
=> Add a11yReviewed frontmatter data to static files

.changeset/brown-cobras-buy.md, docs/content/components/caption.mdx, theme/src/components/horizontal-rule.js, theme/src/components/layout.js, theme/src/components/status-label.js, theme/src/components/superscript.js, theme/src/components/table.js, theme/src/components/wrap-page-element.js, theme/src/components/wrap-root-element.js
Add support and basic styles to support superscripts and footnotes. Aligned them to all [Markdown fields in dotcom](https://github.blog/changelog/2021-09-30-footnotes-now-supported-in-markdown-fields/)
Removed the zebra stripped cells, add functional subtle background on the header, a 🍕  border-radius and use full-width space.
Add `size` prop to adjust its usage to tables
=> Footnotes, Table and StatusLabel styles

theme/package.json, theme/src/components/frame.js, yarn.lock
The [version bump](https://github.com/primer/doctocat/commit/a407024a74b82fc4b82f6e63de64ea6895cf5549) from 4.1.3 to 5.2.1 of react-frame-component seems to have introduced the issue with hard reloading breaking the live examples.
There is an [unresolved, open issue](https://github.com/ryanseddon/react-frame-component/pull/207) in react-frame-component so I looked into if the dependency could be removed. The suggested change works for me in Firefox, Safari and Chrome.
=> Fix live examples disappearing on hard reload

.changeset/heavy-apples-relate.md, docs/content/components/caption.mdx, theme/src/components/layout.js
=> Adjust accessibility labels

.changeset/young-cobras-battle.md, docs/content/usage/customization.mdx, theme/src/components/nav-items.js
Adds support for two levels of nesting in `nav.yml`:
```diff
- title: Introduction
children:
- title: Getting started
-       url: /getting-started
+       children:
+         - title: React
+           url: /getting-started/react
```
Note: Items with `children` cannot also have URLs.
=> Support two levels of nesting in nav.yml

.changeset/proud-horses-know.md, theme/src/primer-nav.yml
As part of https://github.com/primer/primer.style/pull/354 we're removing news.
=> Remove news

.changeset/tricky-toys-unite.md, theme/src/primer-nav.yml
Merge after: https://github.com/primer/design/pull/376
As part of https://github.com/primer/design/pull/376 we're merging the Command Line within the design docs.
=> Remove Command line

.changeset/two-pumpkins-trade.md, theme/src/primer-nav.yml
Following merging https://github.com/primer/design/pull/379
We can remove the mobile menu item as it's part of our design guidelines now.
=> Remove `mobile` from the menu

.changeset/hungry-ads-grab.md, theme/src/components/heading.js
Closes https://github.com/github/primer/issues/1856
=> Move heading permalinks to after headings

.changeset/wet-cobras-nail.md, theme/src/components/container.js, theme/src/components/header.js, theme/src/components/hero-layout.js, theme/src/components/layout.js, theme/src/components/mobile-search.js, theme/src/components/nav-items.js, theme/src/components/page-footer.js, theme/src/components/search.js, theme/src/components/text-input.js, theme/src/components/visually-hidden.js
- Wrap main content in `<main>` that is linked to by the skip nav
- Wrap header in `<header>`
- Wrap footer in `<footer>`
- Add visually hidden h3 to label site navigation
- Add a search icon to search input
- Improve color contrast of search input placeholder text
Closes https://github.com/github/primer/issues/1811
=> Miscellaneous a11y improvements

.changeset/young-cheetahs-sell.md, theme/src/components/header.js, theme/src/components/layout.js, theme/src/components/nav-items.js, theme/src/components/page-footer.js, theme/src/components/wrap-page-element.js
A couple of accessibility improvements:
@colebemis Sorry I ended up re-vising a couple of things I had you add. One small note on this pr I was not having luck getting `yarn workspace docs develop` to run so moving the navigation heading has not been tested.
=> fix a couple of accessibility issues

.changeset/six-rings-smile.md, theme/src/components/wrap-root-element.js
The primer/design project sees thousands of the following warning messages logged on every deploy:
```
When server rendering, you must wrap your application in an <SSRProvider>
```
I believe they are now impacting our ability to deploy, as builds take > 1.5 hours. I've never actually seen one finish. This may be the culprit.
=> Wrap root node with `SSRProvider`

.changeset/eight-suns-scream.md, theme/src/components/layout.js
Relates to: https://github.com/github/primer/issues/1827
If a page has ancestry, it will render a breadcrumb navigation at the top. Parent pages without a `url` set in `nav.yaml` are excluded from the breadcrumb.
The breadcrumb data comes from the site's `nav.yaml` data.
=> Add breadcrumb nav to default layout

.changeset/slow-cycles-search.md, theme/src/components/heading.js, theme/src/components/layout.js
Relates to https://github.com/github/primer/issues/2427
Note: we decided not to change the table of contents link color to blue
Before:
After:
=> Base layout design updates

theme/src/components/header.js
Looks like fontWeight: bold was added to the nav links, which is appearing on primer.style/design 
Removing to revert back to original styles
=> Remove bold weight from top header links

.changeset/cool-balloons-begin.md, theme/src/components/layout.js, theme/src/components/nav-items.js
Fixes minor visual issues
- Aligned with @kendallgassner we could safely move the heading out of the sidebar Navigation. This fixes the extra divider on top of the navigation.
<table>
<tr>
<th> Before</th> <th> After </th>
</tr>
<tr>
<td valign="top">
</td>
<td valign="top">
</td>
</tr>
</table>
- Remove extra space below the heading when there's no status or external links
<table>
<tr>
<th> Before</th> <th> After </th>
</tr>
<tr>
<td valign="top">
</td>
<td valign="top">
</td>
</tr>
</table>
- Remove extra space when there's no `Breadcrumbs`
<table>
<tr>
<th> Before</th> <th> After </th>
</tr>
<tr>
<td valign="top">
</td>
<td valign="top">
</td>
</tr>
</table>
=> Spacing and navigation fixes

.changeset/forty-paws-yawn.md, theme/src/components/header.js, theme/src/components/nav-drawer.js, theme/src/components/text-input.js, theme/src/primer-nav.yml
<table>
<tr>
<th> Before</th> <th> After </th>
</tr>
<tr>
<td valign="top">
</td>
<td valign="top">
</td>
</tr>
</table>
=> About us link and style fixes

.changeset/friendly-dodos-shave.md, theme/src/components/header.js, theme/src/use-path-prefix.js
Add missing `pathPrefix` to the selected state in Underlinenav items
=> Fixes selected state in top navigation

.changeset/fresh-files-melt.md, theme/gatsby-node.js, theme/src/use-search.js
This PR allows adding custom documents (text) to the search mechanism. The use-case is adding Dotcom shared components to search on primer.style, which don't actually have their own pages.
=> Ability to add custom docs to search

.changeset/moody-carrots-know.md, theme/src/components/layout.js
Breadcrumbs links are broken right now on primer.style/design. Testing a fix over in /design/ https://github.com/primer/design/pull/566
Current:
Clicking on the breadcrumb links will 404, the URL is missing `/design/` (see example by clicking on CLI in the breadcrumb https://primer.style/design/native/cli/getting-started)
Expected:
The breadcrumb URL should direct to primer.style/design/`path` , not primer.style/`path`
=> Breadcrumbs fix

package-lock.json, theme/package.json, theme/src/components/drawer.js, theme/src/components/frame.js, theme/src/components/nav-drawer.js
Closes https://github.com/github/primer/issues/2798
Three things to note in this PR
- Add `eslint-plugin-github` onto the `theme` folder's `package.json`.
- Remove `jsx-a11y/click-events-have-key-events` and `jsx-a11y/no-static-element-interactions` using prop redirection. I know this solution is cheeky. But I believe these instances of the lint disables are valid and are not accessibility impediments.Fixing these will get unnecessary pressure off our accessibility scorecard.
=> Add eslint-plugin-github and fix a few disabled a11y rules

package-lock.json, theme/package.json, theme/src/components/header.js, theme/src/components/list.js, theme/src/components/live-code.js, theme/src/components/wrap-root-element.js
Trying to fix the CI issues we're seeing.
* I fixed the Primer React upgrade issue (`<UnderlineNav.Link>` becomes `<UnderlineNav.Item>`).
* I fixed the `styled-components` upgrade issues
However, this revealed an issue with themes. I suspect this is because the `ThemeProvider` is coming from `@primer/react` and build against `styled-components@5` so it's not playing nicely with `styled-components@6`
For now, I've rolled back the `styled-components` version upgrade. We can try this again when it's updated in the dependencies.
=> Fix CI issues 

.changeset/fresh-yaks-battle.md, theme/src/components/live-code.js
Also reverts accidental addition in `theme/src/components/live-code.js`, https://github.com/primer/doctocat/pull/725#pullrequestreview-2008724007,
=> Add changeset

theme/src/components/drawer.js, theme/src/components/nav-drawer.js
Context https://github.com/github/primer/issues/3726
It appears that we no longer need to disable the offending code, as the code itself either is no longer used, or the bug that caused us to disable it has been fixed.
=> Remove `jsx-a11y` disables
