primer/doctocat

theme/gatsby-node.js
theme/package.json

Release 0.14.1

---

theme/gatsby-node.js
theme/package.json
theme/src/components/code.js
theme/src/components/header.js
theme/src/components/nav-items.js
yarn.lock

Release 0.14.2

---

.github/workflows/ci.yml
theme/package.json
theme/src/components/blockquote.js
theme/src/components/dark-text-input.js
theme/src/components/description-list.js
theme/src/components/heading.js
theme/src/components/horizontal-rule.js
theme/src/components/inline-code.js
theme/src/components/list.js
theme/src/components/nav-dropdown.js
theme/src/components/paragraph.js
theme/src/components/table.js
yarn.lock

Upgrades to Primer Components 15.1.0 - needed to update a bunch of `px`instances

Upgrade Primer Components

---

theme/package.json
yarn.lock

forgot to update the yarn lock when i bumped the primer components version 😬

update yarn lock

---

theme/package.json
yarn.lock

It's a long story 😅 Context here: https://github.com/primer/components/pull/643

Update Primer Components again

---

theme/package.json
theme/src/components/header.js
theme/src/components/nav-drawer.js
yarn.lock

> ### 🐛 Bug fixes
> * [x]  Fixed broken page after resizing with navigation drawer open (#113)

Release 0.16.8

---

theme/gatsby-node.js
theme/package.json

* Handle fetching contributor data better
* Fix issue where page frontmatter was lost during HMR builds

Release 0.16.9

---

docs/content/usage/live-code.mdx
theme/package.json
theme/src/components/code.js
theme/src/components/live-code.js

* Add the ability to use `noInline` in live editors via the `noinline` attribute on code blocks (#123)

Release v0.17.0

---

docs/content/getting-started/index.mdx

ZEIT Now is now Vercel.
https://vercel.com/blog/zeit-is-now-vercel

Update information from Now -> Vercel

---

theme/gatsby-node.js
theme/package.json
theme/src/components/live-code.js

Release v0.22.0

---

CONTRIBUTING.md
docs/content/components/caption.mdx
docs/content/usage/local-development.mdx
docs/src/@primer/gatsby-theme-doctocat/nav.yml
theme/package.json
theme/src/components/layout.js

This PR fixes the alignment of the table of contents and adds some requested documentation on running things locally ✨

Fix table of contents alignment + add some docs

---

docs/content/usage/using-images.mdx
docs/src/@primer/gatsby-theme-doctocat/nav.yml

This PR adds some quick docs on how to use local images

Add using images docs

---

.changeset/unlucky-dryers-scream.md
theme/src/primer-nav.yml

Add CLI link to global navigation

---

theme/src/components/frame.js

This fixes https://github.com/primer/doctocat/issues/218

add 6px border radius to FrameComponent

---

theme/src/primer-nav.yml

Add link to `/contribute` site to global nav.

Update global nav

---

.changeset/silver-emus-bathe.md

Adding a changeset to describe the changes in https://github.com/primer/doctocat/pull/247

Add changeset

---

.changeset/great-games-explode.md
theme/src/components/layout.js

Fixes https://github.com/primer/react/issues/1430

Change TOC border color

---

.changeset/rare-cars-build.md

Something strange happened with the last release

Test patch release

---

.changeset/lemon-tomatoes-talk.md
theme/src/components/clipboard-copy.js
theme/src/components/code.js
theme/src/components/contributors.js
theme/src/components/do-dont.js
theme/src/components/drawer.js
theme/src/components/hero-layout.js
theme/src/components/hero.js
theme/src/components/image-container.js
theme/src/components/layout.js
theme/src/components/live-code.js
theme/src/components/mobile-search.js
theme/src/components/nav-drawer.js
theme/src/components/nav-dropdown.js
theme/src/components/nav-items.js
theme/src/components/page-footer.js
theme/src/components/search.js
theme/src/components/sidebar.js
theme/src/components/status-label.js

My changes to PRC to remove styled system prop support caused issues with doctocat's usage.
This PR updates usage of PRC components to use the `sx` prop.

Removes styled system prop usage.

---

.github/workflows/deploy.yml
.github/workflows/deploy_preview.yml

Restoring GitHub API calls in docs

Fix documentation API calls

---

theme/src/components/do-dont.js
theme/src/components/nav-drawer.js
theme/src/components/nav-items.js
theme/src/components/sidebar.js
theme/src/components/table-of-contents.js

Remove unused variables, imports, and props. Also, fix a couple missing hook dependencies.

Fix warnings on `main`

---

theme/src/primer-nav.yml

Goal: Open Source Primer Brand
Adding React Brand to the navigation for [this issue](https://github.com/github/primer/issues/1094).

Update Navigation to Include Brand

---

.changeset/stupid-bottles-agree.md
theme/src/primer-nav.yml

Removed additional slash in primer nav

---

theme/src/components/accessibility-label.js
theme/src/components/layout.js
theme/src/components/status-label.js

Create `AccessibilityLabel` component to avoid duplicated code in the [primer.style/status](www.primer.style/status), [react statuses](https://primer.style/react/status/) and [view component](https://primer.style/view-components/status) statuses.

AccessibilityLabel component

---

.changeset/smart-mangos-destroy.md
theme/package.json
yarn.lock

Bump component-metadata to `v0.5.1`

Update component-metadata library

---

.changeset/real-timers-mate.md
docs/package.json
theme/src/components/header.js
theme/src/components/nav-dropdown.js

Each navigation section should have a header to allow users to quickly jump between sections with their assistive technology.
Also, I noticed the top navigation section is not wrapped in a semantic `nav` tag so I added a `nav`. I also changed the react components of the drop-down nav buttons to use the `ActionMenu` and `ActionList` components instead of detail/summary components (the semantics for these components are a bit more accessible). It definintely changes the look of this navigation section so let me know what you think/if we need to change the ActionMenu button text color. 
I did not tackle responsive mode.

Add visually hidden header to top navigation

---

.changeset/lovely-experts-watch.md
theme/src/components/header.js

Fixes selected state when the path is `undefined`

Fix undefined path

---

theme/src/components/header.js

Just removing a couple of `console.log` statements that made it into `main`.

Remove unnecessary debug statements

---

package-lock.json
theme/package.json
theme/src/components/contributors.js
theme/src/components/header.js

Closes https://github.com/github/primer/issues/2812
1. Aria label should follow sentence casing.
2. Tooltip must wrap over an interactive element. Here `Link` component was wrapping over `Tooltip`. I made the change and also changed the custom css for `Tooltip`. It shows as no change in the documentation for tooltips over contributor avatar links.

Update eslint-plugin-primer-react to latest and fix couple of lint issues

---

.github/workflows/deploy.yml
.github/workflows/deploy_preview.yml

Use tagged version of workflows from .github in actions

Update deploy_preview.yml & deploy.yml

---

.changeset/many-walls-deliver.md
package-lock.json
package.json
theme/package.json

Update gatsby to the latest version in the 3.x line

chore(deps): update gatsby to 3.15.0
